
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;

/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * mainGUI.java
 *
 * Created on May 20, 2009, 9:14:26 PM
 */

/**
 *
 * @author shichan

 */
//DON'T FORGET TO RE-ENABLE RESIZE!!!!! --shicmap

public class mainGUI extends javax.swing.JFrame {

    /** Creates new form mainGUI */
    public mainGUI() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        pwdField = new javax.swing.JPasswordField();
        usernameField = new javax.swing.JTextField();
        usernameLabel = new javax.swing.JLabel();
        pwdLabel = new javax.swing.JLabel();
        signButton = new javax.swing.JButton();
        saveUNPWD = new javax.swing.JCheckBox();
        autoSign = new javax.swing.JCheckBox();
        testLabel = new javax.swing.JLabel();
        parrotim = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Parrot-im");
        setResizable(false);

        pwdField.setHorizontalAlignment(javax.swing.JTextField.LEFT);

        usernameField.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        usernameField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                usernameFieldActionPerformed(evt);
            }
        });

        usernameLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        usernameLabel.setText("Username");

        pwdLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        pwdLabel.setText("Password");

        signButton.setText("Sign in");
        signButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                signButtonActionPerformed(evt);
            }
        });

        saveUNPWD.setText("save username and password");
        saveUNPWD.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveUNPWDActionPerformed(evt);
            }
        });

        autoSign.setText("auto sign in");
        autoSign.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                autoSignActionPerformed(evt);
            }
        });

        testLabel.setText(" ");
        testLabel.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        parrotim.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        parrotim.setText("Parrot-IM");

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/logo_1.png"))); // NOI18N

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .add(48, 48, 48)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(autoSign, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 149, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(saveUNPWD)
                    .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.CENTER)
                        .add(testLabel)
                        .add(layout.createSequentialGroup()
                            .add(usernameLabel)
                            .add(10, 10, 10)
                            .add(usernameField, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                        .add(layout.createSequentialGroup()
                            .add(pwdLabel)
                            .add(13, 13, 13)
                            .add(pwdField, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 159, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                        .add(jLabel1)
                        .add(parrotim)))
                .addContainerGap(52, Short.MAX_VALUE))
            .add(org.jdesktop.layout.GroupLayout.TRAILING, layout.createSequentialGroup()
                .add(112, 112, 112)
                .add(signButton, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 97, Short.MAX_VALUE)
                .add(109, 109, 109))
        );

        layout.linkSize(new java.awt.Component[] {pwdField, usernameField}, org.jdesktop.layout.GroupLayout.HORIZONTAL);

        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(org.jdesktop.layout.GroupLayout.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .add(parrotim, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(jLabel1)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.UNRELATED)
                .add(testLabel)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(usernameField, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(usernameLabel))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(pwdField, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(pwdLabel))
                .add(18, 18, 18)
                .add(saveUNPWD)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(autoSign)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.UNRELATED)
                .add(signButton, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 43, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .add(32, 32, 32))
        );

        layout.linkSize(new java.awt.Component[] {pwdField, usernameField}, org.jdesktop.layout.GroupLayout.VERTICAL);

        pack();
    }// </editor-fold>                        

    private void usernameFieldActionPerformed(java.awt.event.ActionEvent evt) {                                              
        // TODO add your handling code here:
}                                             

    private void signButtonActionPerformed(java.awt.event.ActionEvent evt) {                                           
        // TODO add your handling code here:

        if (usernameField.getText().length() > 0 && pwdField.getPassword().length > 0){
            parrotim.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
            testLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
            testLabel.setText("Please wait, you are being signed in"); //need to fix it,
                                                                       //somehow it's not on the center -Vera

            //set everything invisible during signing in
            usernameLabel.setVisible(false);
            usernameField.setVisible(false);
            pwdLabel.setVisible(false);
            pwdField.setVisible(false);
            saveUNPWD.setVisible(false);
            autoSign.setVisible(false);


            //grey out signButton
            signButton.setEnabled(false);
            signButton.setText("Signing In");
  
            //add an animation here (a rainbow wheel?)
            //for mockup, make it wait.



           // testLabel.setText("                     Signed in                      ");

            //calls next window, close this one? --> move to next frame
            //in flash: loadmovie or goto(frame#)
            
        }else{
            testLabel.setText("Username/password field is empty");
        }
}                                          

    private void saveUNPWDActionPerformed(java.awt.event.ActionEvent evt) {                                          
        // TODO add your handling code here:
}                                         

    private void autoSignActionPerformed(java.awt.event.ActionEvent evt) {                                         
        // TODO add your handling code here:
}                                        

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new mainGUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify                     
    private javax.swing.JCheckBox autoSign;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel parrotim;
    private javax.swing.JPasswordField pwdField;
    private javax.swing.JLabel pwdLabel;
    private javax.swing.JCheckBox saveUNPWD;
    private javax.swing.JButton signButton;
    private javax.swing.JLabel testLabel;
    private javax.swing.JTextField usernameField;
    private javax.swing.JLabel usernameLabel;
    // End of variables declaration                   

}
